name: Check Free Memory

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VANGUARD }}
        username: ${{ secrets.USER }}
        script: whoami
